### ISSUE TITLE
Some nice "quick start" vignettes

### ISSUE THREAD

**Issue by cansavvy** [AlexsLemonade/rOpenScPCA#17]
## Summary 

Just getting going here. Would be nice to have some docs related to quick start for this package. This is somewhat related to #16 What's the thought for what the usage and workflow for this package will look like? 

Is the thought that people will download data following these steps: https://openscpca.readthedocs.io/en/latest/getting-started/accessing-resources/getting-access-to-data/#using-the-download-data-script ?

A bigger question that this leads me to: What's the thought for the audience for this package?

**Comment by jashapiro** [comment]
> A bigger question that this leads me to: What's the thought for the audience for this package?

This package is currently directed mainly toward contributors to OpenScPCA.  The intent is not so much to make a general usage package as to just have a place where common tasks related to OpenScPCA and the specific data/formatting that is used in ScPCA data files. 

I am thinking of it mostly as an itch-scratching package. As we see things that people are frequently doing (and redoing), we can consolidate some of the most useful functions to this package, rather than having people copying code between analysis modules.

**Comment by sjspielman** [comment]
Closing for same reason as #16 - we prefer to keep "vignettes" here housed in `OpenScPCA-analysis` modules! If/when you want to do one of those, we suggest starting with a [`Propose a new analysis` Discussion](https://github.com/AlexsLemonade/OpenScPCA-analysis/discussions/categories/propose-a-new-analysis) and we'll go from there 😃
