### ISSUE TITLE
Seurat conversion fails if there is only one feature for v5 format

### ISSUE THREAD

**Issue by jashapiro** [AlexsLemonade/rOpenScPCA#24]
In rare cases (one in our data) an AltExp may contain only a single feature. This can happen, for example, if cell hashing was performed, but without pooling, so there is only one cellhash antibody with reads. This does not cause trouble for SingleCellExperiment objects, or for v3 Seurat, but v5 Seurat objects _require_ at least two dimensions.

There are a few possible solutions I can think of:
- always use v3 assays if there is only one feature
- add a dummy feature with all zeros to satisfy Seurat
- drop the AltExp

I think I lean toward the dummy feature, but I don't particularly like any of the options!

I'm curious to hear other's thoughts before I implement a fix. Tagging @sjspielman and @jaclyn-taroni for input.

**Comment by sjspielman** [comment]
> I think I lean toward the dummy feature, but I don't particularly like any of the options!

Same I think. None are great, but 1 and 3 seem worse than 2. Removing data altogether is bad, and I don't love the idea of the default assay version not always being the default. Dummy data isn't great either, but if we give a really obvious name (`ceci_nest_pas_une_feature`! only 99% kidding 😄 ) that kind of softens the impact...

I also think we could make this an option and default to choice 2, _but_ since this is such an edge case, it doesn't make sense to me to spend a ton of time coding up different scenarios.

**Comment by jaclyn-taroni** [comment]
Yea, the least bad option seems to be the dummy feature with a really obvious name and some good docs.
